### ISSUE TITLE
1200/2400 Hz tones

### ISSUE THREAD

**Issue by sq2mo** [handiko/Arduino-APRS#4]
I see that you use 1200 and 2400 Hz tones everywhere. Shouldn't APRS use 1200 and **2200**, as originally?

**Comment by handiko** [comment]
Yes you are right. But, for the simplicity i use 1200 and 2400 as they are harmonically related. And most of the APRS decoder can easily decode 1200 & 2400 Hz AFSK.

**Comment by mzakiab** [comment]
audio nya ada di speaker, tapi di bila TX, DireWolf tidak bisa decode. kenapa yer?
